- name: Install foxy dependencies
  become: yes
  apt:
    name:
      - curl
      - gnupg2
      - lsb-release

- name: Download Ros GPG key
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
    dest: /usr/share/keyrings/ros-archive-keyring.gpg

- name: Add repo to sources
  become: yes
  shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null'

- name: Install Ros foxy and colcon
  become: yes
  apt:
    update_cache: yes
    name:
      - ros-foxy-desktop
      - python3-colcon-common-extensions

- name: Add source script to bashrc
  blockinfile:
    path: '{{ ansible_env.HOME }}/.bashrc'
    block: |
      source /opt/ros/{{ ansible_env.ROS_DISTRO }}/setup.bash
      source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash
